# Generated by Django 3.2.14 on 2022-08-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('9.00 - 9.30', '9.00 - 9.30'), ('9.30 - 10.00', '9.30 - 10.00'), ('10.00 - 10.30', '10.00 - 10.30'), ('10.30 - 11.00', '10.30 - 11.00'), ('11.00 - 11.30', '11.00 - 11.30'), ('11.30 - 12.00', '11.30 - 12.00'), ('12.00 - 12.30', '12.00 - 12.30'), ('13.00 - 13.30', '13.00 - 13.30'), ('13.30 - 14.00', '13.30 - 14.00'), ('14.00 - 14.30', '14.00 - 14.30')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
