# Generated by Django 3.2.14 on 2022-07-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220728_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barber',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phonenum',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='booking',
            name='barber',
            field=models.CharField(choices=[('Nathan', 'Nathan'), ('Chris', 'Chris'), ('Ben', 'Ben'), ('Dan', 'Dan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Gents Cut', 'Gents Cut'), ('Kids Cut', 'Kids Cut'), ('Cut and Shave', 'Cut and Shave'), ('Shave Only', 'Shave Only')], max_length=50, null=True),
        ),
    ]
