# Generated by Django 3.2.14 on 2022-07-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimononial',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='testimononial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
