# Generated by Django 3.2.14 on 2022-08-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20220728_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimononial',
            name='updated_on',
        ),
    ]
