# Generated by Django 3.2.14 on 2022-08-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_remove_testimononial_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimononial',
            name='status',
        ),
    ]
